using AutoMapper;
using Core.DTOs.Sensor;
using Core.Entities;
using System;

namespace WebAPI.Models
{
    public class MappingSensor : Profile
    {
        public MappingSensor()
        {
            CreateMap<Sensor, SensorDTO>()
                .ForMember(dest => dest.SensorId,
                    opt => opt.MapFrom(src => src.SensorId))
                .ForMember(dest => dest.SensorCode,
                    opt => opt.MapFrom(src => src.SensorCode))
                .ForMember(dest => dest.SensorName,
                    opt => opt.MapFrom(src => src.SensorName))
                .ForMember(dest => dest.LocationName,
                    opt => opt.MapFrom(src => src.Location != null ? src.Location.LocationName : null))
                .ForMember(dest => dest.AreaName,
                    opt => opt.MapFrom(src => src.Location != null && src.Location.Area != null ? src.Location.Area.AreaName : null))
                .ForMember(dest => dest.SensorStatus,
                    opt => opt.MapFrom(src => src.SensorStatus))
                .ForMember(dest => dest.InstalledAt,
                    opt => opt.MapFrom(src => src.InstalledAt));

            CreateMap<Sensor, SensorDetailDTO>()
                .ForMember(dest => dest.SensorId,
                    opt => opt.MapFrom(src => src.SensorId))
                .ForMember(dest => dest.SensorCode,
                    opt => opt.MapFrom(src => src.SensorCode))
                .ForMember(dest => dest.SensorName,
                    opt => opt.MapFrom(src => src.SensorName))
                .ForMember(dest => dest.SensorType,
                    opt => opt.MapFrom(src => src.SensorType))
                .ForMember(dest => dest.SensorStatus,
                    opt => opt.MapFrom(src => src.SensorStatus))
                .ForMember(dest => dest.InstalledAt,
                    opt => opt.MapFrom(src => src.InstalledAt))
                .ForMember(dest => dest.LocationId,
                    opt => opt.MapFrom(src => src.LocationId))
                .ForMember(dest => dest.MinThreshold,
                    opt => opt.MapFrom(src => src.MinThreshold))
                .ForMember(dest => dest.MaxThreshold,
                    opt => opt.MapFrom(src => src.MaxThreshold))
                .ForMember(dest => dest.ThresholdType,
                    opt => opt.MapFrom(src => src.ThresholdType))
                .ForMember(dest => dest.Location,
                    opt => opt.MapFrom(src => src.Location));


            CreateMap<Location, LocationDetailDTO>()
                .ForMember(dest => dest.LocationId,
                    opt => opt.MapFrom(src => src.LocationId))
                .ForMember(dest => dest.LocationName,
                    opt => opt.MapFrom(src => src.LocationName))
                .ForMember(dest => dest.Address,
                    opt => opt.MapFrom(src => src.Address))
                .ForMember(dest => dest.Latitude,
                    opt => opt.MapFrom(src => src.Latitude))
                .ForMember(dest => dest.Longitude,
                    opt => opt.MapFrom(src => src.Longitude))
                .ForMember(dest => dest.AreaId,
                    opt => opt.MapFrom(src => src.AreaId))
                .ForMember(dest => dest.AreaName,
                    opt => opt.MapFrom(src => src.Area != null ? src.Area.AreaName : null));


            CreateMap<CreateSensorDTO, Sensor>()
                .ForMember(dest => dest.SensorId,
                    opt => opt.Ignore()) // Auto-generated by database
                .ForMember(dest => dest.SensorCode,
                    opt => opt.MapFrom(src => src.SensorCode))
                .ForMember(dest => dest.SensorName,
                    opt => opt.MapFrom(src => src.SensorName))
                .ForMember(dest => dest.SensorType,
                    opt => opt.MapFrom(src => src.SensorType))
                .ForMember(dest => dest.SensorStatus,
                    opt => opt.MapFrom(src => src.SensorStatus))
                .ForMember(dest => dest.InstalledAt,
                    opt => opt.MapFrom(src => src.InstalledAt))
                .ForMember(dest => dest.LocationId,
                    opt => opt.MapFrom(src => src.LocationId))
                .ForMember(dest => dest.Location,
                    opt => opt.Ignore());// Không map navigation property
                                         //.ForMember(dest => dest.MinThreshold,
                                         //    opt => opt.Ignore()) // Set to null initially
                                         //.ForMember(dest => dest.MaxThreshold,
                                         //    opt => opt.Ignore())
                                         //.ForMember(dest => dest.ThresholdType,
                                         //    opt => opt.Ignore());

            CreateMap<UpdateSensorDTO, Sensor>()
                        .ForMember(dest => dest.SensorId,
                            opt => opt.Ignore()) // Không update ID
                        .ForMember(dest => dest.SensorCode,
                            opt => opt.Ignore()) // Không update Code
                        .ForMember(dest => dest.InstalledAt,
                            opt => opt.Ignore()) // Không update ngày cài đặt
                        .ForMember(dest => dest.Location,
                            opt => opt.Ignore()) // Không map navigation property
                        .ForMember(dest => dest.SensorName,
                            opt => opt.MapFrom(src => src.SensorName))
                        .ForMember(dest => dest.SensorType,
                            opt => opt.MapFrom(src => src.SensorType))
                        .ForMember(dest => dest.SensorStatus,
                            opt => opt.MapFrom(src => src.SensorStatus))
                        .ForMember(dest => dest.LocationId,
                            opt => opt.MapFrom(src => src.LocationId))
                        .ForAllMembers(opts => opts.Condition((src, dest, srcMember) => srcMember != null));

            // ============================================
            // MAPPING CHO UPDATE LOCATION
            // ============================================
            CreateMap<UpdateLocationDTO, Location>()
                .ForMember(dest => dest.LocationId,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LocationName,
                    opt => opt.Ignore())
                .ForMember(dest => dest.AreaId,
                    opt => opt.Ignore())
                .ForMember(dest => dest.Area,
                    opt => opt.Ignore())
                .ForMember(dest => dest.Latitude,
                    opt => opt.MapFrom(src => src.Latitude))
                .ForMember(dest => dest.Longitude,
                    opt => opt.MapFrom(src => src.Longitude))
                .ForMember(dest => dest.Address,
                    opt => opt.MapFrom(src => src.Address));

            // ============================================
            // MAPPING CHO UPDATE THRESHOLD
            // ============================================
            CreateMap<UpdateThresholdDTO, Sensor>()
                .ForMember(dest => dest.SensorId,
                    opt => opt.Ignore())
                .ForMember(dest => dest.SensorCode,
                    opt => opt.Ignore())
                .ForMember(dest => dest.SensorName,
                    opt => opt.Ignore())
                .ForMember(dest => dest.SensorType,
                    opt => opt.Ignore())
                .ForMember(dest => dest.SensorStatus,
                    opt => opt.Ignore())
                .ForMember(dest => dest.InstalledAt,
                    opt => opt.Ignore())
                .ForMember(dest => dest.LocationId,
                    opt => opt.Ignore())
                .ForMember(dest => dest.Location,
                    opt => opt.Ignore());
            //.ForMember(dest => dest.MinThreshold,
            //    opt => opt.MapFrom(src => src.MinThreshold))
            //.ForMember(dest => dest.MaxThreshold,
            //    opt => opt.MapFrom(src => src.MaxThreshold))
            //.ForMember(dest => dest.ThresholdType,
            //    opt => opt.MapFrom(src => src.ThresholdType));

        }
    }
}